import type { IntakeAnswers, IntakeRole, IntakeProject, IntakeVersion } from '../types';

/**
 * Compile intake answers into the three markdown documents the app expects.
 * The headers must match what src/lib/parsers/compass.ts and src/lib/ai/materials.ts
 * (extractSection, extractRules) look for — changing them will break scoring and
 * materials generation silently.
 */
export function compileIntake(answers: IntakeAnswers): {
  book: string;
  compass: string;
  playbook: string;
} {
  return {
    book: compileBook(answers),
    compass: compileCompass(answers),
    playbook: compilePlaybook(answers),
  };
}

// ----------------------------------------------------------------------------
// Book
// ----------------------------------------------------------------------------

function compileBook(a: IntakeAnswers): string {
  const out: string[] = [];

  out.push(`# ${a.name || 'Your Name'}: Possible Futures`);
  out.push('');
  out.push('_Generated by Possible Futures, First Printing._');
  out.push('');

  // Contact
  out.push('## Contact');
  out.push('');
  if (a.name) out.push(`- **Name:** ${a.name}`);
  if (a.email) out.push(`- **Email:** ${a.email}`);
  if (a.location) out.push(`- **Location:** ${a.location}`);
  if (a.website) out.push(`- **Website:** ${a.website}`);
  if (a.education && a.education.length > 0) {
    out.push('- **Education:**');
    for (const ed of a.education) {
      const year = ed.year ? `, ${ed.year}` : '';
      out.push(`  - ${ed.degree}, ${ed.school}${year}`);
    }
  }
  out.push('');

  // Positioning
  out.push('## Positioning');
  out.push('');
  out.push(a.through_line || '_(not yet written)_');
  out.push('');

  // AI Scoring Context — used by the prompt builder
  out.push('## AI Scoring Context');
  out.push('');
  out.push(
    'The following shapes how this candidate evaluates opportunities. Consider these bullets when scoring job postings.',
  );
  out.push('');
  if (a.current_situation) {
    out.push(`- **Current situation:** ${a.current_situation}`);
  }
  if (a.through_line) {
    out.push(`- **Through-line:** ${a.through_line}`);
  }
  if (a.dream_role) {
    out.push(`- **Dream role:** ${a.dream_role}`);
  }
  if (a.compensation_floor) {
    out.push(`- **Compensation floor:** $${formatMoney(a.compensation_floor)}`);
  }
  if (a.location_constraint) {
    const remote = a.remote_ok === false ? ' (on-site preferred)' : '';
    out.push(`- **Location:** ${a.location_constraint}${remote}`);
  }
  out.push('');

  // Career Timeline
  out.push('## Career Timeline');
  out.push('');
  if (!a.roles || a.roles.length === 0) {
    out.push('_(no roles entered yet)_');
  } else {
    for (const role of a.roles) {
      out.push(...compileRole(role));
    }
  }
  out.push('');

  // Independent Projects
  out.push('## Independent Projects');
  out.push('');
  out.push('_Personal, freelance, or open source work outside of primary employment._');
  out.push('');
  if (!a.projects || a.projects.length === 0) {
    out.push('_(no projects entered yet)_');
  } else {
    for (const p of a.projects) {
      out.push(...compileProject(p));
    }
  }
  out.push('');

  // Recognition
  out.push('## Recognition');
  out.push('');
  if (!a.recognition || a.recognition.length === 0) {
    out.push('_(none listed)_');
  } else {
    for (const item of a.recognition) {
      out.push(`- ${item}`);
    }
  }
  out.push('');

  // Writing Rules — extractRules looks for this header
  out.push('## Writing Rules');
  out.push('');
  out.push('Mandatory voice and style rules for all generated resume and cover letter content.');
  out.push('');
  for (const rule of DEFAULT_WRITING_RULES) {
    out.push(`- ${rule}`);
  }
  if (a.voice_samples && a.voice_samples.length > 0) {
    out.push('');
    out.push('**Phrases that sound like me (for voice calibration):**');
    for (const phrase of a.voice_samples) {
      out.push(`- "${phrase}"`);
    }
  }
  out.push('');

  // Things to Never Say — extractRules looks for this header
  out.push('## Things to Never Say');
  out.push('');
  out.push('Words and phrases that must never appear in generated content, regardless of context.');
  out.push('');
  const bannedWords = (a.banned_words && a.banned_words.length > 0)
    ? a.banned_words
    : DEFAULT_BANNED_WORDS;
  for (const word of bannedWords) {
    out.push(`- "${word}"`);
  }
  out.push('');

  // Sensitive Context — private framing notes
  out.push('## Sensitive Context');
  out.push('');
  out.push('_Private notes on how to frame sensitive parts of this candidate\'s story. Never copy these verbatim into output — use them as guidance only._');
  out.push('');
  if (a.sensitive_context) {
    out.push(a.sensitive_context);
  } else {
    out.push('_(none)_');
  }
  out.push('');

  // Version Strategy — references what's in the Playbook
  out.push('## Version Strategy');
  out.push('');
  out.push('Resume versions and how to choose between them. See APPLICATION_PLAYBOOK.md for the full Role-Type Emphasis Guide.');
  out.push('');
  if (a.versions && a.versions.length > 0) {
    for (const v of a.versions) {
      out.push(`- **Version ${v.letter} — ${v.label}:** ${v.emphasis}`);
    }
  } else {
    for (const v of DEFAULT_VERSIONS) {
      out.push(`- **Version ${v.letter} — ${v.label}:** ${v.emphasis}`);
    }
  }
  out.push('');

  return out.join('\n');
}

function compileRole(role: IntakeRole): string[] {
  const out: string[] = [];
  const end = role.end && role.end.trim() ? role.end : 'Present';
  out.push(`### ${role.title} · ${role.company}`);
  out.push(`_${role.start} – ${end}_`);
  out.push('');
  if (role.summary) {
    out.push(role.summary);
    out.push('');
  }
  if (role.proudest) {
    out.push(`**Proudest of:** ${role.proudest}`);
    out.push('');
  }
  if (role.stack) {
    out.push(`**Stack:** ${role.stack}`);
    out.push('');
  }
  if (role.raw_notes && role.raw_notes.trim()) {
    out.push(role.raw_notes.trim());
    out.push('');
  }
  return out;
}

function compileProject(p: IntakeProject): string[] {
  const out: string[] = [];
  out.push(`### ${p.title}`);
  out.push('');
  if (p.description) {
    out.push(p.description);
    out.push('');
  }
  if (p.stack) {
    out.push(`**Tech:** ${p.stack}`);
    out.push('');
  }
  if (p.serves_versions && p.serves_versions.length > 0) {
    out.push(`**Serves version(s):** ${p.serves_versions.join(', ')}`);
    out.push('');
  }
  return out;
}

// ----------------------------------------------------------------------------
// Compass
// ----------------------------------------------------------------------------

function compileCompass(a: IntakeAnswers): string {
  const out: string[] = [];

  out.push('# Job Search Compass');
  out.push('');
  out.push('_Generated by Possible Futures, First Printing. The rules below shape every job evaluation._');
  out.push('');

  // The question
  out.push('## What Am I Looking For?');
  out.push('');
  out.push(a.dream_role || '_(not yet written)_');
  out.push('');

  // Role tiers
  if (a.role_tiers) {
    out.push('## Role Tiers');
    out.push('');
    out.push('### Tier 1 — Dream');
    for (const r of a.role_tiers.dream || []) out.push(`- ${r}`);
    if ((a.role_tiers.dream || []).length === 0) out.push('_(none)_');
    out.push('');
    out.push('### Tier 2 — Strong Fit');
    for (const r of a.role_tiers.strong || []) out.push(`- ${r}`);
    if ((a.role_tiers.strong || []).length === 0) out.push('_(none)_');
    out.push('');
    out.push('### Tier 3 — Acceptable');
    for (const r of a.role_tiers.acceptable || []) out.push(`- ${r}`);
    if ((a.role_tiers.acceptable || []).length === 0) out.push('_(none)_');
    out.push('');
  }

  // Constraints — must contain "**Compensation floor:**" pattern for parser
  out.push('## Constraints');
  out.push('');
  if (a.compensation_floor !== undefined && a.compensation_floor !== null) {
    out.push(`- **Compensation floor:** $${formatMoney(a.compensation_floor)}`);
  } else {
    out.push('- **Compensation floor:** $0');
  }
  if (a.location_constraint) {
    out.push(`- **Location:** ${a.location_constraint}`);
  }
  if (a.remote_ok !== undefined) {
    out.push(`- **Remote:** ${a.remote_ok ? 'open' : 'on-site only'}`);
  }
  out.push('');

  // Signal words — parser looks for lines starting with `-` and quoted phrases
  out.push('## Signal Words in Job Postings');
  out.push('');
  out.push('Green flags. Words that mean "pay attention" when they show up in a posting.');
  out.push('');
  if (a.signal_words && a.signal_words.length > 0) {
    for (const word of a.signal_words) {
      out.push(`- "${word}"`);
    }
  } else {
    out.push('- _(none yet)_');
  }
  out.push('');

  // Red flag words — parser looks for the same pattern
  out.push('## Red Flag Words in Job Postings');
  out.push('');
  out.push('Words that mean "reconsider" when they show up in a posting.');
  out.push('');
  if (a.red_flag_words && a.red_flag_words.length > 0) {
    for (const word of a.red_flag_words) {
      out.push(`- "${word}"`);
    }
  } else {
    out.push('- _(none yet)_');
  }
  out.push('');

  out.push('---');
  out.push('');

  // Companies
  out.push('## Companies and Teams to Watch');
  out.push('');
  if (a.target_companies && a.target_companies.length > 0) {
    out.push('### Targets');
    for (const c of a.target_companies) {
      out.push(`- **${c}** — from intake`);
    }
  } else {
    out.push('_(none yet)_');
  }
  out.push('');

  out.push('---');
  out.push('');

  // People — placeholder section (intake doesn't collect people yet)
  out.push('## People Whose Orbits I Want to Be In');
  out.push('');
  out.push('_(none listed — add them from the People page after onboarding)_');
  out.push('');

  out.push('---');
  out.push('');

  // How to score — references the scoring dimensions the app uses
  out.push('## How to Score a Job Posting');
  out.push('');
  out.push('Six dimensions, each scored 0–3:');
  out.push('');
  out.push('| Dimension | Question |');
  out.push('|-----------|----------|');
  out.push('| **Want** | Does the work actually excite me? |');
  out.push('| **Can** | Can I do this well with what I know today? |');
  out.push('| **Grow** | Will I learn something meaningful here? |');
  out.push('| **Pay** | Does compensation meet my floor? |');
  out.push('| **Team** | Will I work with people I respect and learn from? |');
  out.push('| **Impact** | Will what I build actually matter? |');
  out.push('');
  out.push('Max score: 18. Strong fit: 15+. Acceptable: 12–14. Weak: below 12.');
  out.push('');

  return out.join('\n');
}

// ----------------------------------------------------------------------------
// Playbook
// ----------------------------------------------------------------------------

function compilePlaybook(a: IntakeAnswers): string {
  const out: string[] = [];

  out.push('# Application Playbook');
  out.push('');
  out.push('_Generated by Possible Futures, First Printing._');
  out.push('');

  // Resume Rules — extractRules looks for this header
  out.push('## Resume Rules');
  out.push('');
  for (const rule of DEFAULT_RESUME_RULES) {
    out.push(`- ${rule}`);
  }
  out.push('');

  // Cover Letter Rules — extractRules looks for this header
  out.push('## Cover Letter Rules');
  out.push('');
  for (const rule of DEFAULT_COVER_LETTER_RULES) {
    out.push(`- ${rule}`);
  }
  out.push('');

  // Things to Never Do — extractRules looks for this header
  out.push('## Things to Never Do');
  out.push('');
  for (const rule of DEFAULT_NEVER_DO) {
    out.push(`- ${rule}`);
  }
  if (a.banned_words && a.banned_words.length > 0) {
    out.push('- Never use any of these words in generated content:');
    for (const w of a.banned_words) {
      out.push(`  - "${w}"`);
    }
  }
  out.push('');

  // Role-Type Emphasis Guide — getResumeVersionLabels looks for `### Version A: Label`
  out.push('## Role-Type Emphasis Guide');
  out.push('');
  out.push('Which resume version to reach for depending on the role, and what to emphasize.');
  out.push('');
  const versions = (a.versions && a.versions.length > 0) ? a.versions : DEFAULT_VERSIONS;
  for (const v of versions) {
    out.push(`### Version ${v.letter}: ${v.label}`);
    out.push('');
    out.push(v.emphasis || '_(no emphasis notes yet)_');
    if (a.projects) {
      const served = a.projects.filter(
        (p) => p.serves_versions && p.serves_versions.includes(v.letter),
      );
      if (served.length > 0) {
        out.push('');
        out.push('**Emphasize these projects:**');
        for (const p of served) {
          out.push(`- ${p.title}`);
        }
      }
    }
    out.push('');
  }

  return out.join('\n');
}

// ----------------------------------------------------------------------------
// Defaults — generic enough to ship in an open-source release
// ----------------------------------------------------------------------------

function formatMoney(n: number): string {
  return n.toLocaleString('en-US');
}

const DEFAULT_WRITING_RULES = [
  'No em dashes. Use commas or periods.',
  'No "spearheaded," "leveraged," "utilized," "facilitated," "synergy," or "cutting-edge."',
  'No "helped lead." Be specific: either led it or supported it.',
  'Write achievements, not task descriptions.',
  'Put tech stacks in context (e.g., "Built X on Y" not "Proficient in Y").',
  'No inflated or fake metrics. If no number exists, frame the outcome honestly.',
  'Confident but not arrogant. Direct but not robotic.',
  'First person implied (no "I" in bullets), but the voice should feel human.',
];

const DEFAULT_BANNED_WORDS = [
  'spearheaded',
  'leveraged',
  'utilized',
  'facilitated',
  'synergy',
  'cutting-edge',
  'rockstar',
  'ninja',
  'guru',
  'self-taught',
];

const DEFAULT_RESUME_RULES = [
  'Two pages max. No exceptions.',
  'Lead with the clearest title for the role, then a 3-4 sentence summary that mirrors the posting.',
  'Tailor the summary to each role. Never send the same summary twice.',
  'Keep roles in reverse chronological order under Experience.',
  'Use sans-serif fonts (Arial or similar) for ATS compatibility.',
  'No photo, no "References available upon request," no objective statement.',
];

const DEFAULT_COVER_LETTER_RULES = [
  'Three paragraphs max. Long cover letters do not get read.',
  'Role-specific from line one. No career autobiography openers.',
  'Write genuinely different letters for each role.',
  'Lead with insight or specificity, not a narrative of your whole career.',
];

const DEFAULT_NEVER_DO = [
  'Never paste the same cover letter into two applications.',
  'Never promise skills you do not actually have.',
  'Never include a photo, an objective statement, or "References available upon request."',
  'Never send a resume without reading the posting first.',
];

const DEFAULT_VERSIONS: IntakeVersion[] = [
  {
    letter: 'A',
    label: 'Primary',
    emphasis: 'Your default resume. Balanced view of your strongest skills and most relevant experience.',
  },
  {
    letter: 'B',
    label: 'Technical',
    emphasis: 'For roles that emphasize depth. Lead with specific technologies, architectures, and measurable outcomes.',
  },
  {
    letter: 'C',
    label: 'Leadership',
    emphasis: 'For roles where managing people or projects matters. Emphasize team size, cross-functional work, and strategic impact.',
  },
  {
    letter: 'D',
    label: 'Specialist',
    emphasis: 'For roles in a specific niche. Tailor heavily to the domain and cut anything that dilutes the focus.',
  },
];

export const INTAKE_DEFAULTS = {
  writing_rules: DEFAULT_WRITING_RULES,
  banned_words: DEFAULT_BANNED_WORDS,
  resume_rules: DEFAULT_RESUME_RULES,
  cover_letter_rules: DEFAULT_COVER_LETTER_RULES,
  never_do: DEFAULT_NEVER_DO,
  versions: DEFAULT_VERSIONS,
};
